---
- hosts: localhost
  connection: local
  vars_files:
    vars.yml
  tasks: 
    - name: set hostname
      hostname:
        name: "{{ hostname }}"
    - name: add necesssary repos
      import_tasks: repos.yml
    - name: replace dnf.conf
      file:
        src: dnf.conf
        dest: /etc/dnf/dnf.conf
        owner: root
        group: root
        mode: 0644
    - name: install base packages
      dnf:
        name:
        - buildah 
        - code
        - "@development-tools"
        - dkms 
#        - docker
#        - docker-compose
        - elfutils-libelf-devel 
        - flatpak
        - gnome-shell-extension-dash-to-dock
        - gnome-tweak-tool
        - google-cloud-sdk
        - guake
        - hub
        - ImageMagick
        - jq
        - kernel-devel 
        - kernel-headers
        - krita
        - kubectl
        - NetworkManager-strongswan-gnome 
        - python3-libselinux
        - libnsl
        - mpv
        - npm
        - openshot
        - podman
        - powertop
        - protobuf
        - python3-devel
        - python3-ansible-runner
        - qt5-qtx11extras
        - rclone
        - remmina
        - simple-scan
        - simplescreenrecorder
        - skopeo
        - snapd
        - strongswan
        - teams
        - vinagre
        - vivaldi
        - vlc
        state: present 
        update_cache: yes
      become: yes
      ignore_errors: yes
      tags:
        - packages
#    - name: create docker group
#      group: 
#        name: docker
#        state: present
#      become: yes
#      tags:
#        - packages
#    - name: add user to docker group
#      user: 
#        name: "{{ username }}"
#        group: docker
#        state: present
#      become: yes
#      tags:
#        - packages

    - name: add flatpak repo
      command: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

    - name: install flatpak apps
      command: "flatpak install {{ item.repo }} {{ item.name }} --noninteractive"
      with_items:
        - { name: "com.slack.Slack", repo: "flathub"}
        - { name: "com.obsproject.Studio", repo: "flathub"}
        - { name: "us.zoom.Zoom", repo: "flathub"}

#    - name: add flatpak app aliases

    - name: create snap symlink for classic support
      file: 
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      become: yes
      tags:
        - packages
    - name: install snaps # snap module doesn't come in until 2.8
      command: "snap install {{ item }}"
      become: yes
      with_items: 
        - snap-store
        - spotify
        - postman
        - ramboxpro
        - rocketchat-desktop
#        - bitwarden
        - "helm --classic"
      tags:
        - packages
    - name: install npm items
      npm: 
        name: "{{ item }}"
        state: present
        global: yes
      #  path: ~/npm
      with_items: 
        - nativefier 
      become: yes
      tags:
        - packages
    - name: use nativefier to create apps
      include_tasks: nativefier.yml
      with_items: 
        - { name: notion, url: "https://notion.so"}
      tags:
        - packages
    - name: install opera
      include_tasks: opera.yml 
      tags:
        - packages
    - name: Set git email addy
      command: git config --global user.email "{{ git_email }}"
      tags:
        - config
    - name: Install tools
      import_tasks: cli_tools.yml
      tags:
        - cli_tools
#    - name: Add startup scripts
#      import_tasks: startup_scripts.yml
#      tags:
#        - config
    - name: Set nautilus to show path/address
      command: gsettings set org.gnome.nautilus.preferences always-use-location-entry true
    # - name: install nvidia drivers    ## Doesn't seem to work yet
    #   import_tasks: nvidia.yml
