---
- hosts: localhost
  connection: local
  vars_files:
    vars.yml
  tasks: 
  - name: Add Podman repository key ({{ ansible_distribution }})
    ansible.builtin.apt_key:
      url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key
      state: present
    become: yes

  - name: Create Podman repository ({{ ansible_distribution }})
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
      filename: libcontainers
      state: present
    become: yes
